[address]
#文件格式，以英文#开头是注释，会直接过滤
mst_address = [
    "nimble1y0jv6tw50rq5h4w2dpxu3696vyzrrc59we6ntl",
    
    "nimble1p0srme7smxz9whs0n6sqxj9vl8c8ugcd4nuvtq",
]


sub_address = [
    #子地址
    "nimble12eq5tfzlmjpvqq0k20vxzqwd3fsnxv9rvkzufl",
    

    #子地址
    "nimble1uzatqnpkule7f6w9jddwyvwjfjewzevezadqpm",
    "nimble1t2gxjyu5zgznf5cltet2qknqpafg83fhzu9d4u",

[monitor]
api_report_log="http://5.188.33.88:8888/printlnlog"


[server]
ip="127.0.0.1"
port=8888


[clore]

#web_api_host
web_api_host="https://clore.ai/"
#请求下单接口
web_token="MTcxNzU4MDc0OF9xRHJDWTFMemY2QkdYY3YzVGVTejg1QjVmVmtMS2Q="

#api请求地址
api_host="https://api.clore.ai/"
#api数据接口token
api_token="PJBpQJTPVfFx0q8WSV1-mvfb5NB9kJ8G"
#远程连接密码
ssh_passwd="MTcxNjMwNDc2N19ZempBSW"

command="""
#!/bin/bash
cd $HOME
apt update -y 
apt install git -y
# 设置时区
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
echo "export SERVER_ID={server_id}" >> $HOME/.bashrc
echo "export CARD_NUMBER={card_number}" >> $HOME/.bashrc
echo "export ADDRESS={address}" >> $HOME/.bashrc

source $HOME/.bashrc
git clone  https://github.com/kratos-123/clore.git >> $HOME/server.txt 2>&1

cd $HOME/clore
chmod +x env.sh erust.sh execute.sh && ./env.sh >> $HOME/server.txt 2>&1
mkdir -p $HOME/clore/logs
mv $HOME/server.txt $HOME/clore/
# 防止内部被cd,需要切换到clore目录操作
cd $HOME/clore
source $HOME/.cargo/env
source $HOME/.bashrc

# 激活pm2环境,用pm2管理cargo 监控进程
conda init
conda activate nimble
cargo run -r --bin  monitor  -- > $HOME/clore/monitor.txt 2>&1 &
"""





